// Transcript → beat constants. Reads whisper JSON (word-level), emits engine/generated/beats.ts
// Optional argv: node cli/beats.mjs [transcriptPath] [outPath]
//   e.g. node cli/beats.mjs demo/input/transcript2.json engine/generated/beats2.ts
import fs from "node:fs";

const transcriptPath = process.argv[2] ?? "demo/input/transcript.json";
const outPath = process.argv[3] ?? "engine/generated/beats.ts";

const t = JSON.parse(fs.readFileSync(transcriptPath, "utf8"));
const words = t.transcription
  .map((w) => ({ text: w.text.trim(), startMs: w.offsets.from, endMs: w.offsets.to }))
  .filter((w) => w.text.length > 0);

const out = `// AUTO-GENERATED by cli/beats.mjs from ${transcriptPath} — do not edit.
export const FPS = 30;
export type Word = { text: string; startMs: number; endMs: number };
export const WORDS: Word[] = ${JSON.stringify(words)};
export const msToFrame = (ms: number): number => Math.round((ms * FPS) / 1000);
`;
fs.mkdirSync("engine/generated", { recursive: true });
fs.writeFileSync(outPath, out);
console.log(`wrote ${outPath} (${words.length} words, last ends ${words.at(-1).endMs}ms)`);
